### ISSUE TITLE
Horizontal scrolling is broken on desktop

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#592]
Clicking the arrows does nothing, only "dragging" works but the behavior is really weird, it keeps moving by itself (as if we set some constant scrolling velocity).

Single clicks (that do nothing) result with the following console error:

> content.js:7  Uncaught TypeError: Cannot read properties of undefined (reading '0')
>     at Array.<anonymous> (content.js:7:88744)
>     at c.trigger (content.js:7:81786)
>     at HTMLDocument.<anonymous> (content.js:7:81311)
> (anonymous) @ content.js:7
> c.trigger @ content.js:7
> (anonymous) @ content.js:7
> Show 3 more frames
> Show less
> content.js:7  Uncaught TypeError: Cannot read properties of undefined (reading '0')
>     at content.js:7:89004
> (anonymous) @ content.js:7
> setTimeout (async)
> (anonymous) @ content.js:7
> c.trigger @ content.js:7
> (anonymous) @ content.js:7
> Show 4 more frames
> Show less
> content.js:7  Uncaught TypeError: Cannot read properties of undefined (reading '0')
>     at Array.<anonymous> (content.js:7:89199)
>     at c.trigger (content.js:7:81786)
>     at HTMLDocument.<anonymous> (content.js:7:81253)

**Comment by 4tal** [comment]
For me works as expected
Mac.

**Comment by omer-friedman** [comment]
@ohadschn 
can you please post a short video? I can't reproduce the bug as you described.

**Comment by ohadschn** [comment]
> @ohadschn can you please post a short video? I'm not sure I understand the bug

Let's focus on the simple and most important issue, which doesn't require a video - I click the horizontal scrolling arrows (recently added by Idan) and nothing happens. The console displays the error I pasted in the original post.

**Comment by omer-friedman** [comment]
@ohadschn I added this feature. and I still cant reproduce the bug. it works both in Chrome and Edge (Windows)

https://github.com/4tals/LinksForIsrael/assets/34510256/dc6b3c72-2a70-4068-b31b-df2f07b50548

**Comment by ohadschn** [comment]
> @ohadschn I added this feature. and I still cant reproduce the bug. it works both in Chrome and Edge (Windows)

I played with it some more, and it looks like the behavior is something like "scroll in an amount proportionate to the length of the click".

So my usual clicks are really fast and do nothing, but if I keep the mouse button pressed down for a moment, and then release, I the scrolling happens.
